name: dcat
description: a simple DCAT tool
version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
dependencies:
  args: ^2.3.0
  convert: ^3.0.2
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
